from __future__ import annotations

import math
import re
import sqlite3
import time

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager

# ------------------- konfiguracja -------------------
PLAYERS: list[str] = [
    "https://www.sofascore.com/pl/zawodnik/alexis-mac-allister/895324",
    "https://www.sofascore.com/pl/zawodnik/alisson/243609",
    "https://www.sofascore.com/pl/zawodnik/andrew-robertson/262911",
    "https://www.sofascore.com/pl/zawodnik/bradley-conor/1008402",
    "https://www.sofascore.com/pl/zawodnik/caoimhin-kelleher/827362",
    "https://www.sofascore.com/pl/zawodnik/cody-gakpo/862967",
    "https://www.sofascore.com/pl/zawodnik/curtis-jones/927353",
    "https://www.sofascore.com/pl/zawodnik/darwin-nunez/924871",
    "https://www.sofascore.com/pl/zawodnik/davies-harvey/1008403",
    "https://www.sofascore.com/pl/zawodnik/diogo-jota/606164",
    "https://www.sofascore.com/pl/zawodnik/dominik-szoboszlai/869856",
    "https://www.sofascore.com/pl/zawodnik/federico-chiesa/845386",
    "https://www.sofascore.com/pl/zawodnik/harvey-elliott/955245",
    "https://www.sofascore.com/pl/zawodnik/ibrahima-konate/826215",
    "https://www.sofascore.com/pl/zawodnik/isaac-mabaya/1148511",
    "https://www.sofascore.com/pl/zawodnik/jarell-quansah/1003339",
    "https://www.sofascore.com/pl/zawodnik/joe-gomez/318927",
    "https://www.sofascore.com/pl/zawodnik/konstantinos-tsimikas/786259",
    "https://www.sofascore.com/pl/zawodnik/luis-diaz/883537",
    "https://www.sofascore.com/pl/zawodnik/mohamed-salah/159665",
    "https://www.sofascore.com/pl/zawodnik/ryan-gravenberch/904897",
    "https://www.sofascore.com/pl/zawodnik/trent-alexander-arnold/795064",
    "https://www.sofascore.com/pl/zawodnik/tyler-morton/979118",
    "https://www.sofascore.com/pl/zawodnik/virgil-van-dijk/151545",
    "https://www.sofascore.com/pl/zawodnik/vitezslav-jaros/927359",
    "https://www.sofascore.com/pl/zawodnik/wataru-endo/143040",
    "https://www.sofascore.com/pl/zawodnik/benjamin-white/846036",
    "https://www.sofascore.com/pl/zawodnik/bukayo-saka/934235",
    "https://www.sofascore.com/pl/zawodnik/butler-oyedeji-nathan/998835",
    "https://www.sofascore.com/pl/zawodnik/charles-sagoe-jr/1119436",
    "https://www.sofascore.com/pl/zawodnik/david-raya/581310",
    "https://www.sofascore.com/pl/zawodnik/declan-rice/856714",
    "https://www.sofascore.com/pl/zawodnik/ethan-nwaneri/1401702",
    "https://www.sofascore.com/pl/zawodnik/gabriel-jesus/794839",
    "https://www.sofascore.com/pl/zawodnik/gabriel-magalhaes/869792",
    "https://www.sofascore.com/pl/zawodnik/gabriel-martinelli/922573",
    "https://www.sofascore.com/pl/zawodnik/ismeal-kabia/1621612",
    "https://www.sofascore.com/pl/zawodnik/jack-henry-francis/1110078",
    "https://www.sofascore.com/pl/zawodnik/jimi-gower/1411034",
    "https://www.sofascore.com/pl/zawodnik/jorginho/132874",
    "https://www.sofascore.com/pl/zawodnik/jurrien-timber/958959",
    "https://www.sofascore.com/pl/zawodnik/kai-havertz/836705",
    "https://www.sofascore.com/pl/zawodnik/kieran-tierney/366592",
    "https://www.sofascore.com/pl/zawodnik/kiwior-jakub/976037",
    "https://www.sofascore.com/pl/zawodnik/leandro-trossard/135666",
    "https://www.sofascore.com/pl/zawodnik/lewis-skelly-myles/1423711",
    "https://www.sofascore.com/pl/zawodnik/martin-odegaard/547410",
    "https://www.sofascore.com/pl/zawodnik/mikel-merino/592010",
    "https://www.sofascore.com/pl/zawodnik/neto/84844",
    "https://www.sofascore.com/pl/zawodnik/oleksandr-zinchenko/287643",
    "https://www.sofascore.com/pl/zawodnik/raheem-sterling/138534",
    "https://www.sofascore.com/pl/zawodnik/riccardo-calafiori/957602",
    "https://www.sofascore.com/pl/zawodnik/thomas-partey/316148",
    "https://www.sofascore.com/pl/zawodnik/tomiyasu-takehiro/804434",
    "https://www.sofascore.com/pl/zawodnik/tommy-setford/1150958",
    "https://www.sofascore.com/pl/zawodnik/william-saliba/941168",
    "https://www.sofascore.com/pl/zawodnik/alexander-isak/823941",
    "https://www.sofascore.com/pl/zawodnik/bruno-guimaraes/866469",
    "https://www.sofascore.com/pl/zawodnik/callum-wilson/113956",
    "https://www.sofascore.com/pl/zawodnik/dan-burn/99090",
    "https://www.sofascore.com/pl/zawodnik/emil-krafth/150396",
    "https://www.sofascore.com/pl/zawodnik/fabian-schar/101882",
    "https://www.sofascore.com/pl/zawodnik/gordon-anthony/914902",
    "https://www.sofascore.com/pl/zawodnik/harvey-barnes/855647",
    "https://www.sofascore.com/pl/zawodnik/jacob-murphy/372336",
    "https://www.sofascore.com/pl/zawodnik/jamaal-lascelles/153444",
    "https://www.sofascore.com/pl/zawodnik/jamal-lewis/891803",
    "https://www.sofascore.com/pl/zawodnik/joe-willock/888550",
    "https://www.sofascore.com/pl/zawodnik/joelinton/560128",
    "https://www.sofascore.com/pl/zawodnik/john-ruddy/1131",
    "https://www.sofascore.com/pl/zawodnik/kieran-trippier/69256",
    "https://www.sofascore.com/pl/zawodnik/lewis-hall/1136730",
    "https://www.sofascore.com/pl/zawodnik/lewis-miley/1400650",
    "https://www.sofascore.com/pl/zawodnik/mark-gillespie/108508",
    "https://www.sofascore.com/pl/zawodnik/martin-dubravka/42209",
    "https://www.sofascore.com/pl/zawodnik/matt-targett/368134",
    "https://www.sofascore.com/pl/zawodnik/nick-pope/162653",
    "https://www.sofascore.com/pl/zawodnik/odysseas-vlachodimos/138149",
    "https://www.sofascore.com/pl/zawodnik/osula-william/1122603",
    "https://www.sofascore.com/pl/zawodnik/sandro-tonali/892673",
    "https://www.sofascore.com/pl/zawodnik/sean-longstaff/866191",
    "https://www.sofascore.com/pl/zawodnik/sean-neave/1511675",
    "https://www.sofascore.com/pl/zawodnik/sven-botman/910046",
    "https://www.sofascore.com/pl/zawodnik/valentino-livramento/980634",
    "https://www.sofascore.com/pl/zawodnik/abdukodir-khusanov/1194333",
    "https://www.sofascore.com/pl/zawodnik/bernardo-silva/331209",
    "https://www.sofascore.com/pl/zawodnik/claudio-echeverri/1482424",
    "https://www.sofascore.com/pl/zawodnik/ederson/254491",
    "https://www.sofascore.com/pl/zawodnik/erling-haaland/839956",
    "https://www.sofascore.com/pl/zawodnik/ilkay-gundogan/45853",
    "https://www.sofascore.com/pl/zawodnik/jack-grealish/189061",
    "https://www.sofascore.com/pl/zawodnik/james-mcatee/1003334",
    "https://www.sofascore.com/pl/zawodnik/jeremy-doku/934386",
    "https://www.sofascore.com/pl/zawodnik/john-stones/152077",
    "https://www.sofascore.com/pl/zawodnik/josko-gvardiol/964994",
    "https://www.sofascore.com/pl/zawodnik/kevin-de-bruyne/70996",
    "https://www.sofascore.com/pl/zawodnik/manuel-akanji/383560",
    "https://www.sofascore.com/pl/zawodnik/mateo-kovacic/136710",
    "https://www.sofascore.com/pl/zawodnik/matheus-nunes/945122",
    "https://www.sofascore.com/pl/zawodnik/nathan-ake/149663",
    "https://www.sofascore.com/pl/zawodnik/nico-gonzalez/954056",
    "https://www.sofascore.com/pl/zawodnik/nico-o-reilly/1142703",
    "https://www.sofascore.com/pl/zawodnik/omar-marmoush/873554",
    "https://www.sofascore.com/pl/zawodnik/oscar-bobb/1065216",
    "https://www.sofascore.com/pl/zawodnik/phil-foden/859765",
    "https://www.sofascore.com/pl/zawodnik/reis-vitor/1485300",
    "https://www.sofascore.com/pl/zawodnik/rico-lewis/1136731",
    "https://www.sofascore.com/pl/zawodnik/rodri/827606",
    "https://www.sofascore.com/pl/zawodnik/ruben-dias/318941",
    "https://www.sofascore.com/pl/zawodnik/savio/1046795",
    "https://www.sofascore.com/pl/zawodnik/scott-carson/716",
    "https://www.sofascore.com/pl/zawodnik/stefan-ortega/125274",
    "https://www.sofascore.com/pl/zawodnik/anselmino-aaron/1500263",
    "https://www.sofascore.com/pl/zawodnik/benoit-badiashile/904827",
    "https://www.sofascore.com/pl/zawodnik/christopher-nkunku/769333",
    "https://www.sofascore.com/pl/zawodnik/cole-palmer/982780",
    "https://www.sofascore.com/pl/zawodnik/david-datro-fofana/1090458",
    "https://www.sofascore.com/pl/zawodnik/dewsbury-hall-kiernan/861970",
    "https://www.sofascore.com/pl/zawodnik/enzo-fernandez/974505",
    "https://www.sofascore.com/pl/zawodnik/filip-jorgensen/962053",
    "https://www.sofascore.com/pl/zawodnik/genesis-antwi/1402709",
    "https://www.sofascore.com/pl/zawodnik/guiu-marc/1414933",
    "https://www.sofascore.com/pl/zawodnik/gusto-malo/996958",
    "https://www.sofascore.com/pl/zawodnik/ishe-samuels-smith/1196791",
    "https://www.sofascore.com/pl/zawodnik/josh-acheampong/1403050",
    "https://www.sofascore.com/pl/zawodnik/landon-emenalo/1881891",
    "https://www.sofascore.com/pl/zawodnik/levi-colwill/996911",
    "https://www.sofascore.com/pl/zawodnik/lucas-bergstrom/996903",
    "https://www.sofascore.com/pl/zawodnik/marc-cucurella/794939",
    "https://www.sofascore.com/pl/zawodnik/marcus-bettinelli/257993",
    "https://www.sofascore.com/pl/zawodnik/mathis-amougou/1426224",
    "https://www.sofascore.com/pl/zawodnik/moises-caicedo/987650",
    "https://www.sofascore.com/pl/zawodnik/mykhaylo-mudryk/958966",
    "https://www.sofascore.com/pl/zawodnik/nicolas-jackson/1085381",
    "https://www.sofascore.com/pl/zawodnik/noni-madueke/966547",
    "https://www.sofascore.com/pl/zawodnik/omari-kellyman/1162083",
    "https://www.sofascore.com/pl/zawodnik/pedro-neto/879349",
    "https://www.sofascore.com/pl/zawodnik/reece-james/885908",
    "https://www.sofascore.com/pl/zawodnik/reggie-walsh/1913033",
    "https://www.sofascore.com/pl/zawodnik/robert-sanchez/920546",
    "https://www.sofascore.com/pl/zawodnik/romeo-lavia/1069488",
    "https://www.sofascore.com/pl/zawodnik/sam-rak-sakyi/1150955",
    "https://www.sofascore.com/pl/zawodnik/sancho-jadon/851100",
    "https://www.sofascore.com/pl/zawodnik/shumaira-mheuka/1402787",
    "https://www.sofascore.com/pl/zawodnik/tosin-adarabioyo/352668",
    "https://www.sofascore.com/pl/zawodnik/trevoh-chalobah/826134",
    "https://www.sofascore.com/pl/zawodnik/tyrique-george/1403061",
    "https://www.sofascore.com/pl/zawodnik/wesley-fofana/923894",
    "https://www.sofascore.com/pl/zawodnik/abbott-zach/1390490",
    "https://www.sofascore.com/pl/zawodnik/alex-moreno/294593",
    "https://www.sofascore.com/pl/zawodnik/anthony-elanga/979232",
    "https://www.sofascore.com/pl/zawodnik/callum-hudson-odoi/867442",
    "https://www.sofascore.com/pl/zawodnik/carlos-miguel/973738",
    "https://www.sofascore.com/pl/zawodnik/chris-wood/50480",
    "https://www.sofascore.com/pl/zawodnik/danilo/1064039",
    "https://www.sofascore.com/pl/zawodnik/elliot-anderson/994546",
    "https://www.sofascore.com/pl/zawodnik/eric-da-silva-moreira/1418646",
    "https://www.sofascore.com/pl/zawodnik/harry-toffolo/358218",
    "https://www.sofascore.com/pl/zawodnik/ibrahim-sangare/843754",
    "https://www.sofascore.com/pl/zawodnik/jota-silva/1011895",
    "https://www.sofascore.com/pl/zawodnik/matz-sels/78152",
    "https://www.sofascore.com/pl/zawodnik/morato/985086",
    "https://www.sofascore.com/pl/zawodnik/morgan-gibbs-white/865912",
    "https://www.sofascore.com/pl/zawodnik/murillo/1199282",
    "https://www.sofascore.com/pl/zawodnik/nicolas-dominguez/871765",
    "https://www.sofascore.com/pl/zawodnik/nikola-milenkovic/836168",
    "https://www.sofascore.com/pl/zawodnik/ola-aina/800417",
    "https://www.sofascore.com/pl/zawodnik/ramon-sosa/1015733",
    "https://www.sofascore.com/pl/zawodnik/ryan-yates/846252",
    "https://www.sofascore.com/pl/zawodnik/taiwo-awoniyi/359664",
    "https://www.sofascore.com/pl/zawodnik/wayne-hennessey/16620",
    "https://www.sofascore.com/pl/zawodnik/williams-neco/927356",
    "https://www.sofascore.com/pl/zawodnik/willy-boly/139310",
    "https://www.sofascore.com/pl/zawodnik/amadou-onana/923973",
    "https://www.sofascore.com/pl/zawodnik/andres-garcia/1457536",
    "https://www.sofascore.com/pl/zawodnik/axel-disasi/827243",
    "https://www.sofascore.com/pl/zawodnik/boubacar-kamara/826204",
    "https://www.sofascore.com/pl/zawodnik/donyell-malen/803039",
    "https://www.sofascore.com/pl/zawodnik/emiliano-martinez/158263",
    "https://www.sofascore.com/pl/zawodnik/ezri-konsa/827679",
    "https://www.sofascore.com/pl/zawodnik/ian-maatsen/976263",
    "https://www.sofascore.com/pl/zawodnik/jacob-ramsey/975937",
    "https://www.sofascore.com/pl/zawodnik/jamaldeen-jimoh/1410178",
    "https://www.sofascore.com/pl/zawodnik/john-mcginn/250223",
    "https://www.sofascore.com/pl/zawodnik/kortney-hause/255189",
    "https://www.sofascore.com/pl/zawodnik/lamare-bogarde/1089388",
    "https://www.sofascore.com/pl/zawodnik/leon-bailey/808590",
    "https://www.sofascore.com/pl/zawodnik/lucas-digne/96538",
    "https://www.sofascore.com/pl/zawodnik/marco-asensio/361004",
    "https://www.sofascore.com/pl/zawodnik/marcus-rashford/814590",
    "https://www.sofascore.com/pl/zawodnik/matty-cash/833956",
    "https://www.sofascore.com/pl/zawodnik/morgan-rogers/948261",
    "https://www.sofascore.com/pl/zawodnik/ollie-watkins/555386",
    "https://www.sofascore.com/pl/zawodnik/pau-torres/864169",
    "https://www.sofascore.com/pl/zawodnik/robin-olsen/26025",
    "https://www.sofascore.com/pl/zawodnik/ross-barkley/98435",
    "https://www.sofascore.com/pl/zawodnik/tyrone-mings/303638",
    "https://www.sofascore.com/pl/zawodnik/youri-tielemans/331737",
    "https://www.sofascore.com/pl/zawodnik/adama-traore/286165",
    "https://www.sofascore.com/pl/zawodnik/alex-iwobi/352770",
    "https://www.sofascore.com/pl/zawodnik/andreas-pereira/285949",
    "https://www.sofascore.com/pl/zawodnik/antonee-robinson/803174",
    "https://www.sofascore.com/pl/zawodnik/bernd-leno/103335",
    "https://www.sofascore.com/pl/zawodnik/calvin-bassey/861972",
    "https://www.sofascore.com/pl/zawodnik/carlos-vinicius/891920",
    "https://www.sofascore.com/pl/zawodnik/emile-smith-rowe/867445",
    "https://www.sofascore.com/pl/zawodnik/harrison-reed/365802",
    "https://www.sofascore.com/pl/zawodnik/harry-wilson/355528",
    "https://www.sofascore.com/pl/zawodnik/issa-diop/825719",
    "https://www.sofascore.com/pl/zawodnik/joachim-andersen/362682",
    "https://www.sofascore.com/pl/zawodnik/jorge-cuenca/868715",
    "https://www.sofascore.com/pl/zawodnik/joshua-king/1546231",
    "https://www.sofascore.com/pl/zawodnik/kenny-tete/190877",
    "https://www.sofascore.com/pl/zawodnik/martial-godo/1190938",
    "https://www.sofascore.com/pl/zawodnik/raul-jimenez/192442",
    "https://www.sofascore.com/pl/zawodnik/reiss-nelson/826139",
    "https://www.sofascore.com/pl/zawodnik/rodrigo-muniz/1015256",
    "https://www.sofascore.com/pl/zawodnik/ryan-sessegnon/836698",
    "https://www.sofascore.com/pl/zawodnik/sander-berge/793167",
    "https://www.sofascore.com/pl/zawodnik/sasa-lukic/371222",
    "https://www.sofascore.com/pl/zawodnik/steven-benda/860764",
    "https://www.sofascore.com/pl/zawodnik/timothy-castagne/329417",
    "https://www.sofascore.com/pl/zawodnik/tom-cairney/82566",
    "https://www.sofascore.com/pl/zawodnik/willian/31417",
    "https://www.sofascore.com/pl/zawodnik/adam-webster/216308",
    "https://www.sofascore.com/pl/zawodnik/baleba-carlos/1199043",
    "https://www.sofascore.com/pl/zawodnik/bart-verbruggen/994363",
    "https://www.sofascore.com/pl/zawodnik/carl-rushworth/1005800",
    "https://www.sofascore.com/pl/zawodnik/cashin-eiran-joe/998928",
    "https://www.sofascore.com/pl/zawodnik/charlie-tasker/1543802",
    "https://www.sofascore.com/pl/zawodnik/danny-welbeck/33902",
    "https://www.sofascore.com/pl/zawodnik/diego-gomez/1065588",
    "https://www.sofascore.com/pl/zawodnik/ferdi-kadioglu/825844",
    "https://www.sofascore.com/pl/zawodnik/freddie-simmonds/1546225",
    "https://www.sofascore.com/pl/zawodnik/gruda-brajan/1198075",
    "https://www.sofascore.com/pl/zawodnik/igor-julio/842513",
    "https://www.sofascore.com/pl/zawodnik/jack-hinshelwood/1142315",
    "https://www.sofascore.com/pl/zawodnik/james-milner/791",
    "https://www.sofascore.com/pl/zawodnik/jan-paul-van-hecke/962012",
    "https://www.sofascore.com/pl/zawodnik/jason-steele/31867",
    "https://www.sofascore.com/pl/zawodnik/joao-pedro/975079",
    "https://www.sofascore.com/pl/zawodnik/joel-veltman/219572",
    "https://www.sofascore.com/pl/zawodnik/lamptey-tariq/914691",
    "https://www.sofascore.com/pl/zawodnik/lewis-dunk/115365",
    "https://www.sofascore.com/pl/zawodnik/mats-wieffer/959628",
    "https://www.sofascore.com/pl/zawodnik/matt-oriley/891829",
    "https://www.sofascore.com/pl/zawodnik/minteh-yankuba/1400106",
    "https://www.sofascore.com/pl/zawodnik/mitoma-kaoru/936849",
    "https://www.sofascore.com/pl/zawodnik/pervis-estupinan/805465",
    "https://www.sofascore.com/pl/zawodnik/rutter-georginio/946695",
    "https://www.sofascore.com/pl/zawodnik/simon-adingra/1110842",
    "https://www.sofascore.com/pl/zawodnik/solly-march/301288",
    "https://www.sofascore.com/pl/zawodnik/tom-mcgill/1007073",
    "https://www.sofascore.com/pl/zawodnik/yasin-ayari/1036269",
    "https://www.sofascore.com/pl/zawodnik/adam-smith/44566",
    "https://www.sofascore.com/pl/zawodnik/alex-scott/1104986",
    "https://www.sofascore.com/pl/zawodnik/antoine-semenyo/934354",
    "https://www.sofascore.com/pl/zawodnik/ben-winterburn/2007889",
    "https://www.sofascore.com/pl/zawodnik/dango-ouattara/1106451",
    "https://www.sofascore.com/pl/zawodnik/daniel-jebbison/1096136",
    "https://www.sofascore.com/pl/zawodnik/david-brooks/855731",
    "https://www.sofascore.com/pl/zawodnik/dean-huijsen/1176744",
    "https://www.sofascore.com/pl/zawodnik/enes-unal/336655",
    "https://www.sofascore.com/pl/zawodnik/evanilson/998490",
    "https://www.sofascore.com/pl/zawodnik/illia-zabarnyi/1023567",
    "https://www.sofascore.com/pl/zawodnik/james-hill/1156586",
    "https://www.sofascore.com/pl/zawodnik/julian-araujo/978150",
    "https://www.sofascore.com/pl/zawodnik/julio-soler/1201520",
    "https://www.sofascore.com/pl/zawodnik/justin-kluivert/851596",
    "https://www.sofascore.com/pl/zawodnik/kepa-arrizabalaga/232422",
    "https://www.sofascore.com/pl/zawodnik/lewis-cook/548188",
    "https://www.sofascore.com/pl/zawodnik/luis-sinisterra/836070",
    "https://www.sofascore.com/pl/zawodnik/marcos-senesi/830659",
    "https://www.sofascore.com/pl/zawodnik/marcus-tavernier/895576",
    "https://www.sofascore.com/pl/zawodnik/matai-akinmboni/1190712",
    "https://www.sofascore.com/pl/zawodnik/milos-kerkez/1097425",
    "https://www.sofascore.com/pl/zawodnik/ryan-christie/322391",
    "https://www.sofascore.com/pl/zawodnik/sadi-dominic/1398550",
    "https://www.sofascore.com/pl/zawodnik/tyler-adams/800419",
    "https://www.sofascore.com/pl/zawodnik/will-dennis/991001",
    "https://www.sofascore.com/pl/zawodnik/ben-mee/137774",
    "https://www.sofascore.com/pl/zawodnik/bryan-mbeumo/927083",
    "https://www.sofascore.com/pl/zawodnik/christian-norgaard/135256",
    "https://www.sofascore.com/pl/zawodnik/damsgaard-mikkel/907072",
    "https://www.sofascore.com/pl/zawodnik/ethan-pinnock/855864",
    "https://www.sofascore.com/pl/zawodnik/fabio-carvalho/991604",
    "https://www.sofascore.com/pl/zawodnik/gustavo-nunes/1514747",
    "https://www.sofascore.com/pl/zawodnik/hakon-rafn-valdimarsson/1005959",
    "https://www.sofascore.com/pl/zawodnik/hickey-aaron/966869",
    "https://www.sofascore.com/pl/zawodnik/igor-thiago/1016907",
    "https://www.sofascore.com/pl/zawodnik/joshua-dasilva/856260",
    "https://www.sofascore.com/pl/zawodnik/keane-lewis-potter/972421",
    "https://www.sofascore.com/pl/zawodnik/kevin-schade/1006387",
    "https://www.sofascore.com/pl/zawodnik/kim-ji-soo/1185061",
    "https://www.sofascore.com/pl/zawodnik/kristoffer-ajer/576384",
    "https://www.sofascore.com/pl/zawodnik/maghoma-edmond-paris/907500",
    "https://www.sofascore.com/pl/zawodnik/mark-flekken/171919",
    "https://www.sofascore.com/pl/zawodnik/mathias-jensen/799251",
    "https://www.sofascore.com/pl/zawodnik/michael-kayode/1137431",
    "https://www.sofascore.com/pl/zawodnik/nathan-collins/958916",
    "https://www.sofascore.com/pl/zawodnik/rico-henry/599128",
    "https://www.sofascore.com/pl/zawodnik/sepp-van-den-berg/924378",
    "https://www.sofascore.com/pl/zawodnik/vitaly-janelt/814873",
    "https://www.sofascore.com/pl/zawodnik/yarmoliuk-yehor/1031258",
    "https://www.sofascore.com/pl/zawodnik/yoane-wissa/805123",
    "https://www.sofascore.com/pl/zawodnik/yunus-konak/1518589",
    "https://www.sofascore.com/pl/zawodnik/adam-wharton/1109771",
    "https://www.sofascore.com/pl/zawodnik/ben-chilwell/802695",
    "https://www.sofascore.com/pl/zawodnik/caleb-kporha/1465401",
    "https://www.sofascore.com/pl/zawodnik/chadi-riad/1064218",
    "https://www.sofascore.com/pl/zawodnik/cheick-doucoure/906047",
    "https://www.sofascore.com/pl/zawodnik/chris-richards/931844",
    "https://www.sofascore.com/pl/zawodnik/daichi-kamada/794338",
    "https://www.sofascore.com/pl/zawodnik/daniel-munoz/870360",
    "https://www.sofascore.com/pl/zawodnik/dean-henderson/788134",
    "https://www.sofascore.com/pl/zawodnik/devenny-justin/1084311",
    "https://www.sofascore.com/pl/zawodnik/eberechi-eze/864921",
    "https://www.sofascore.com/pl/zawodnik/ebiowei-malcolm/1176104",
    "https://www.sofascore.com/pl/zawodnik/edward-nketiah/858194",
    "https://www.sofascore.com/pl/zawodnik/ismaila-sarr/845286",
    "https://www.sofascore.com/pl/zawodnik/jean-philippe-mateta/848276",
    "https://www.sofascore.com/pl/zawodnik/jefferson-lerma/355796",
    "https://www.sofascore.com/pl/zawodnik/joel-ward/39183",
    "https://www.sofascore.com/pl/zawodnik/kaden-rodney/1185603",
    "https://www.sofascore.com/pl/zawodnik/marc-guehi/877994",
    "https://www.sofascore.com/pl/zawodnik/matheus-franca/1116593",
    "https://www.sofascore.com/pl/zawodnik/matt-turner/833943",
    "https://www.sofascore.com/pl/zawodnik/maxence-lacroix/879674",
    "https://www.sofascore.com/pl/zawodnik/nathaniel-clyne/43215",
    "https://www.sofascore.com/pl/zawodnik/remi-matthews/581610",
    "https://www.sofascore.com/pl/zawodnik/romain-esse/1438837",
    "https://www.sofascore.com/pl/zawodnik/tyrick-mitchell/988275",
    "https://www.sofascore.com/pl/zawodnik/will-hughes/193554",
    "https://www.sofascore.com/pl/zawodnik/andre/1035996",
    "https://www.sofascore.com/pl/zawodnik/bastien-meupiyou/1405973",
    "https://www.sofascore.com/pl/zawodnik/boubacar-traore/982613",
    "https://www.sofascore.com/pl/zawodnik/carlos-borges/1069486",
    "https://www.sofascore.com/pl/zawodnik/craig-dawson/50027",
    "https://www.sofascore.com/pl/zawodnik/daniel-bentley/101367",
    "https://www.sofascore.com/pl/zawodnik/emmanuel-agbadou/1013842",
    "https://www.sofascore.com/pl/zawodnik/enso-gonzalez/1402232",
    "https://www.sofascore.com/pl/zawodnik/gomes-rodrigo/1006073",
    "https://www.sofascore.com/pl/zawodnik/goncalo-guedes/280979",
    "https://www.sofascore.com/pl/zawodnik/hee-chan-hwang/786186",
    "https://www.sofascore.com/pl/zawodnik/jean-ricner-bellegarde/845273",
    "https://www.sofascore.com/pl/zawodnik/joao-gomes/1015267",
    "https://www.sofascore.com/pl/zawodnik/jorgen-strand-larsen/876599",
    "https://www.sofascore.com/pl/zawodnik/jose-sa/252669",
    "https://www.sofascore.com/pl/zawodnik/lima-pedro/1597270",
    "https://www.sofascore.com/pl/zawodnik/marshall-munetsi/894733",
    "https://www.sofascore.com/pl/zawodnik/mateus-mane/1899647",
    "https://www.sofascore.com/pl/zawodnik/matheus-cunha/886363",
    "https://www.sofascore.com/pl/zawodnik/matt-doherty/143047",
    "https://www.sofascore.com/pl/zawodnik/nasser-djiga/1127169",
    "https://www.sofascore.com/pl/zawodnik/nathan-fraser/1166679",
    "https://www.sofascore.com/pl/zawodnik/nelson-semedo/252821",
    "https://www.sofascore.com/pl/zawodnik/pablo-sarabia/138573",
    "https://www.sofascore.com/pl/zawodnik/rayan-ait-nouri/931278",
    "https://www.sofascore.com/pl/zawodnik/sam-johnstone/98427",
    "https://www.sofascore.com/pl/zawodnik/santiago-bueno/846308",
    "https://www.sofascore.com/pl/zawodnik/sasa-kalajdzic/870038",
    "https://www.sofascore.com/pl/zawodnik/tom-king/603922",
    "https://www.sofascore.com/pl/zawodnik/tommy-doyle/932628",
    "https://www.sofascore.com/pl/zawodnik/toti-gomes/973418",
    "https://www.sofascore.com/pl/zawodnik/yerson-mosquera/1014835",
    "https://www.sofascore.com/pl/zawodnik/alejandro-garnacho/1135873",
    "https://www.sofascore.com/pl/zawodnik/altay-bayindir/815890",
    "https://www.sofascore.com/pl/zawodnik/amass-harry/1461595",
    "https://www.sofascore.com/pl/zawodnik/andre-onana/787498",
    "https://www.sofascore.com/pl/zawodnik/bruno-fernandes/288205",
    "https://www.sofascore.com/pl/zawodnik/casemiro/122951",
    "https://www.sofascore.com/pl/zawodnik/chido-obi/1566204",
    "https://www.sofascore.com/pl/zawodnik/christian-eriksen/105734",
    "https://www.sofascore.com/pl/zawodnik/diallo-amad/971037",
    "https://www.sofascore.com/pl/zawodnik/diogo-dalot/843200",
    "https://www.sofascore.com/pl/zawodnik/dorgu-patrick/1397168",
    "https://www.sofascore.com/pl/zawodnik/godwill-kukonki/1899546",
    "https://www.sofascore.com/pl/zawodnik/harry-maguire/149380",
    "https://www.sofascore.com/pl/zawodnik/heaven-ayden/1445799",
    "https://www.sofascore.com/pl/zawodnik/jack-fletcher/1402726",
    "https://www.sofascore.com/pl/zawodnik/jack-lee-moorhouse/1533758",
    "https://www.sofascore.com/pl/zawodnik/jonny-evans/30144",
    "https://www.sofascore.com/pl/zawodnik/joshua-zirkzee/917007",
    "https://www.sofascore.com/pl/zawodnik/kobbie-mainoo/1142175",
    "https://www.sofascore.com/pl/zawodnik/leny-yoro/1153315",
    "https://www.sofascore.com/pl/zawodnik/lisandro-martinez/859999",
    "https://www.sofascore.com/pl/zawodnik/luke-shaw/190839",
    "https://www.sofascore.com/pl/zawodnik/manuel-ugarte/846425",
    "https://www.sofascore.com/pl/zawodnik/mason-mount/836694",
    "https://www.sofascore.com/pl/zawodnik/matthijs-de-ligt/803031",
    "https://www.sofascore.com/pl/zawodnik/noussair-mazraoui/847030",
    "https://www.sofascore.com/pl/zawodnik/rasmus-hojlund/1086417",
    "https://www.sofascore.com/pl/zawodnik/toby-collyer/1084356",
    "https://www.sofascore.com/pl/zawodnik/tom-heaton/18122",
    "https://www.sofascore.com/pl/zawodnik/tyler-fredricson/1142182",
    "https://www.sofascore.com/pl/zawodnik/victor-lindelof/143334",
    "https://www.sofascore.com/pl/zawodnik/abdoulaye-doucoure/96535",
    "https://www.sofascore.com/pl/zawodnik/armando-broja/996985",
    "https://www.sofascore.com/pl/zawodnik/ashley-young/10589",
    "https://www.sofascore.com/pl/zawodnik/asmir-begovic/13918",
    "https://www.sofascore.com/pl/zawodnik/beto/987489",
    "https://www.sofascore.com/pl/zawodnik/carlos-alcaraz/1017392",
    "https://www.sofascore.com/pl/zawodnik/dominic-calvert-lewin/372344",
    "https://www.sofascore.com/pl/zawodnik/dwight-mcneil/935543",
    "https://www.sofascore.com/pl/zawodnik/idrissa-gueye/106337",
    "https://www.sofascore.com/pl/zawodnik/iliman-ndiaye/914309",
    "https://www.sofascore.com/pl/zawodnik/jack-harrison/829570",
    "https://www.sofascore.com/pl/zawodnik/jake-obrien/998253",
    "https://www.sofascore.com/pl/zawodnik/james-garner/927361",
    "https://www.sofascore.com/pl/zawodnik/james-tarkowski/145188",
    "https://www.sofascore.com/pl/zawodnik/jarrad-branthwaite/979563",
    "https://www.sofascore.com/pl/zawodnik/jesper-lindstrom/947929",
    "https://www.sofascore.com/pl/zawodnik/joao-virginia/930666",
    "https://www.sofascore.com/pl/zawodnik/jordan-pickford/138530",
    "https://www.sofascore.com/pl/zawodnik/michael-keane/110846",
    "https://www.sofascore.com/pl/zawodnik/orel-mangala/793988",
    "https://www.sofascore.com/pl/zawodnik/patterson-nathan/1020141",
    "https://www.sofascore.com/pl/zawodnik/seamus-coleman/76632",
    "https://www.sofascore.com/pl/zawodnik/tim-iroegbunam/1085950",
    "https://www.sofascore.com/pl/zawodnik/vitaliy-mykolenko/876643",
    "https://www.sofascore.com/pl/zawodnik/youssef-chermiti/1145627",
    "https://www.sofascore.com/pl/zawodnik/alfie-whiteman/822504",
    "https://www.sofascore.com/pl/zawodnik/antonin-kinsky/1031251",
    "https://www.sofascore.com/pl/zawodnik/archie-gray/1142335",
    "https://www.sofascore.com/pl/zawodnik/austin-brandon/859896",
    "https://www.sofascore.com/pl/zawodnik/ben-davies/94758",
    "https://www.sofascore.com/pl/zawodnik/bentancur-rodrigo/791190",
    "https://www.sofascore.com/pl/zawodnik/bergvall-lucas/1391251",
    "https://www.sofascore.com/pl/zawodnik/brennan-johnson/1085180",
    "https://www.sofascore.com/pl/zawodnik/cristian-romero/829932",
    "https://www.sofascore.com/pl/zawodnik/danso-kevin/794953",
    "https://www.sofascore.com/pl/zawodnik/dejan-kulusevski/928124",
    "https://www.sofascore.com/pl/zawodnik/destiny-udogie/983572",
    "https://www.sofascore.com/pl/zawodnik/djed-spence/945798",
    "https://www.sofascore.com/pl/zawodnik/dominic-solanke/361420",
    "https://www.sofascore.com/pl/zawodnik/fraser-forster/19314",
    "https://www.sofascore.com/pl/zawodnik/guglielmo-vicario/553606",
    "https://www.sofascore.com/pl/zawodnik/heung-min-son/111505",
    "https://www.sofascore.com/pl/zawodnik/james-maddison/356398",
    "https://www.sofascore.com/pl/zawodnik/mathys-tel/1048888",
    "https://www.sofascore.com/pl/zawodnik/micky-van-de-ven/998247",
    "https://www.sofascore.com/pl/zawodnik/mikey-moore/1403192",
    "https://www.sofascore.com/pl/zawodnik/pape-matar-sarr/1002711",
    "https://www.sofascore.com/pl/zawodnik/pedro-porro/913654",
    "https://www.sofascore.com/pl/zawodnik/radu-dragusin/997103",
    "https://www.sofascore.com/pl/zawodnik/richarlison/840217",
    "https://www.sofascore.com/pl/zawodnik/scarlett-dane/998772",
    "https://www.sofascore.com/pl/zawodnik/sergio-reguilon/858195",
    "https://www.sofascore.com/pl/zawodnik/timo-werner/232306",
    "https://www.sofascore.com/pl/zawodnik/wilson-odobert/1142679",
    "https://www.sofascore.com/pl/zawodnik/yves-bissouma/844842",
    "https://www.sofascore.com/pl/zawodnik/aaron-cresswell/43443",
    "https://www.sofascore.com/pl/zawodnik/aaron-wan-bissaka/863653",
    "https://www.sofascore.com/pl/zawodnik/alphonse-areola/96531",
    "https://www.sofascore.com/pl/zawodnik/andy-irving/845464",
    "https://www.sofascore.com/pl/zawodnik/carlos-soler/832427",
    "https://www.sofascore.com/pl/zawodnik/crysencio-summerville/917005",
    "https://www.sofascore.com/pl/zawodnik/danny-ings/130181",
    "https://www.sofascore.com/pl/zawodnik/edson-alvarez/847151",
    "https://www.sofascore.com/pl/zawodnik/emerson-palmieri/155997",
    "https://www.sofascore.com/pl/zawodnik/evan-ferguson/999231",
    "https://www.sofascore.com/pl/zawodnik/guido-rodriguez/609752",
    "https://www.sofascore.com/pl/zawodnik/james-ward-prowse/161717",
    "https://www.sofascore.com/pl/zawodnik/jarrod-bowen/552884",
    "https://www.sofascore.com/pl/zawodnik/jean-clair-todibo/945217",
    "https://www.sofascore.com/pl/zawodnik/konstantinos-mavropanos/829022",
    "https://www.sofascore.com/pl/zawodnik/lucas-paqueta/839981",
    "https://www.sofascore.com/pl/zawodnik/luis-guilherme/1464248",
    "https://www.sofascore.com/pl/zawodnik/lukasz-fabianski/15479",
    "https://www.sofascore.com/pl/zawodnik/max-kilman/894474",
    "https://www.sofascore.com/pl/zawodnik/michail-antonio/47772",
    "https://www.sofascore.com/pl/zawodnik/mohammed-kudus/905163",
    "https://www.sofascore.com/pl/zawodnik/niclas-fullkrug/132645",
    "https://www.sofascore.com/pl/zawodnik/scarles-oliver/1150952",
    "https://www.sofascore.com/pl/zawodnik/tomas-soucek/799041",
    "https://www.sofascore.com/pl/zawodnik/vladimir-coufal/138024",
    "https://www.sofascore.com/pl/zawodnik/wesley-foderingham/187861",
    "https://www.sofascore.com/pl/zawodnik/alex-palmer/796143",
    "https://www.sofascore.com/pl/zawodnik/arijanet-muric/888971",
    "https://www.sofascore.com/pl/zawodnik/axel-tuanzebe/817979",
    "https://www.sofascore.com/pl/zawodnik/ben-godfrey/754698",
    "https://www.sofascore.com/pl/zawodnik/ben-johnson/914412",
    "https://www.sofascore.com/pl/zawodnik/cameron-burgess/358084",
    "https://www.sofascore.com/pl/zawodnik/christian-walton/198038",
    "https://www.sofascore.com/pl/zawodnik/cieran-slicker/1001845",
    "https://www.sofascore.com/pl/zawodnik/conor-chaplin/784625",
    "https://www.sofascore.com/pl/zawodnik/conor-townsend/197982",
    "https://www.sofascore.com/pl/zawodnik/dara-oshea/856719",
    "https://www.sofascore.com/pl/zawodnik/george-hirst/839712",
    "https://www.sofascore.com/pl/zawodnik/jack-clarke/921005",
    "https://www.sofascore.com/pl/zawodnik/jack-taylor/856669",
    "https://www.sofascore.com/pl/zawodnik/jacob-greaves/990821",
    "https://www.sofascore.com/pl/zawodnik/jaden-philogene-bidace/1014461",
    "https://www.sofascore.com/pl/zawodnik/jens-cajuste/857671",
    "https://www.sofascore.com/pl/zawodnik/julio-enciso/973556",
    "https://www.sofascore.com/pl/zawodnik/kalvin-phillips/786028",
    "https://www.sofascore.com/pl/zawodnik/leif-davis/963493",
    "https://www.sofascore.com/pl/zawodnik/liam-delap/997087",
    "https://www.sofascore.com/pl/zawodnik/luke-woolfenden/893478",
    "https://www.sofascore.com/pl/zawodnik/massimo-luongo/204300",
    "https://www.sofascore.com/pl/zawodnik/nathan-broadhead/911710",
    "https://www.sofascore.com/pl/zawodnik/ogbene-chiedozie/849309",
    "https://www.sofascore.com/pl/zawodnik/omari-hutchinson/1090963",
    "https://www.sofascore.com/pl/zawodnik/sam-morsy/108515",
    "https://www.sofascore.com/pl/zawodnik/sammie-szmodics/354782",
    "https://www.sofascore.com/pl/zawodnik/somto-boniface/1595095",
    "https://www.sofascore.com/pl/zawodnik/tom-taylor/1901423",
    "https://www.sofascore.com/pl/zawodnik/wes-burns/305302",
    "https://www.sofascore.com/pl/zawodnik/abdul-fatawu-issahaku/1103589",
    "https://www.sofascore.com/pl/zawodnik/bilal-el-khannouss/1126569",
    "https://www.sofascore.com/pl/zawodnik/bobby-decordova-reid/151499",
    "https://www.sofascore.com/pl/zawodnik/boubakary-soumare/887581",
    "https://www.sofascore.com/pl/zawodnik/caleb-okoli/967722",
    "https://www.sofascore.com/pl/zawodnik/conor-coady/98449",
    "https://www.sofascore.com/pl/zawodnik/daniel-iversen/796986",
    "https://www.sofascore.com/pl/zawodnik/danny-ward/197428",
    "https://www.sofascore.com/pl/zawodnik/facundo-buonanotte/1117025",
    "https://www.sofascore.com/pl/zawodnik/harry-souttar/808680",
    "https://www.sofascore.com/pl/zawodnik/harry-winks/545780",
    "https://www.sofascore.com/pl/zawodnik/jake-evans/1899501",
    "https://www.sofascore.com/pl/zawodnik/jakub-stolarczyk/997830",
    "https://www.sofascore.com/pl/zawodnik/james-justin/827681",
    "https://www.sofascore.com/pl/zawodnik/jamie-vardy/173827",
    "https://www.sofascore.com/pl/zawodnik/jannik-vestergaard/120538",
    "https://www.sofascore.com/pl/zawodnik/jeremy-monga/1861707",
    "https://www.sofascore.com/pl/zawodnik/jordan-ayew/103045",
    "https://www.sofascore.com/pl/zawodnik/kasey-mcateer/1065134",
    "https://www.sofascore.com/pl/zawodnik/kristiansen-victor/1092409",
    "https://www.sofascore.com/pl/zawodnik/luke-thomas/991584",
    "https://www.sofascore.com/pl/zawodnik/mads-hermansen/856640",
    "https://www.sofascore.com/pl/zawodnik/michael-golding/1403055",
    "https://www.sofascore.com/pl/zawodnik/odsonne-edouard/795228",
    "https://www.sofascore.com/pl/zawodnik/patson-daka/865057",
    "https://www.sofascore.com/pl/zawodnik/ricardo-pereira/221200",
    "https://www.sofascore.com/pl/zawodnik/skipp-oliver/859901",
    "https://www.sofascore.com/pl/zawodnik/stephy-mavididi/605338",
    "https://www.sofascore.com/pl/zawodnik/wilfred-ndidi/787885",
    "https://www.sofascore.com/pl/zawodnik/wout-faes/361696",
    "https://www.sofascore.com/pl/zawodnik/woyo-coulibaly/989894",
    "https://www.sofascore.com/pl/zawodnik/aaron-ramsdale/839410",
    "https://www.sofascore.com/pl/zawodnik/adam-lallana/17054",
    "https://www.sofascore.com/pl/zawodnik/albert-gronbaek/1000263",
    "https://www.sofascore.com/pl/zawodnik/alex-mccarthy/45502",
    "https://www.sofascore.com/pl/zawodnik/armel-bella-kotchap/976025",
    "https://www.sofascore.com/pl/zawodnik/cameron-archer/993451",
    "https://www.sofascore.com/pl/zawodnik/charlie-taylor/166381",
    "https://www.sofascore.com/pl/zawodnik/flynn-downes/879810",
    "https://www.sofascore.com/pl/zawodnik/jack-stephens/134361",
    "https://www.sofascore.com/pl/zawodnik/james-bree/555406",
    "https://www.sofascore.com/pl/zawodnik/jan-bednarek/286085",
    "https://www.sofascore.com/pl/zawodnik/jay-robinson/1440673",
    "https://www.sofascore.com/pl/zawodnik/joe-aribo/818073",
    "https://www.sofascore.com/pl/zawodnik/joe-lumley/591620",
    "https://www.sofascore.com/pl/zawodnik/juan-larios/1134532",
    "https://www.sofascore.com/pl/zawodnik/kamaldeen-sulemana/1019442",
    "https://www.sofascore.com/pl/zawodnik/kyle-walker-peters/823085",
    "https://www.sofascore.com/pl/zawodnik/lesley-ugochukwu/1048916",
    "https://www.sofascore.com/pl/zawodnik/mateus-fernandes/1142562",
    "https://www.sofascore.com/pl/zawodnik/nathan-wood/944200",
    "https://www.sofascore.com/pl/zawodnik/paul-onuachu/295123",
    "https://www.sofascore.com/pl/zawodnik/ross-stewart/886117",
    "https://www.sofascore.com/pl/zawodnik/ryan-fraser/138261",
    "https://www.sofascore.com/pl/zawodnik/ryan-manning/328701",
    "https://www.sofascore.com/pl/zawodnik/sanda-joachim-kayi/1426220",
    "https://www.sofascore.com/pl/zawodnik/takaoka-rento/1501646",
    "https://www.sofascore.com/pl/zawodnik/taylor-harwood-bellis/980637",
    "https://www.sofascore.com/pl/zawodnik/tyler-dibling/1174472",
    "https://www.sofascore.com/pl/zawodnik/welington/1009920",
    "https://www.sofascore.com/pl/zawodnik/will-smallbone/970435",
    "https://www.sofascore.com/pl/zawodnik/yukinari-sugawara/905347",
]


LABELS = {
    "Rozegrane łącznie":           "matches",
    "Rozegrane minuty":            "minutes",
    "Bramki":                      "goals",
    "Strzały":                     "shots",
    "Asysty":                      "assists",
    "Przechwyty":                  "interceptions",
    "Piłki odebrane na mecz":      "ball_recoveries",
    "Przedryblowania na mecz":     "times_dribbled_past",
    "Udane dryblingi":             "successful_dribbles",
    "Wygrane pojedynki":           "duels_won",
    "Faule na mecz":               "fouls",
    "Żółte kartki":                "yellow",
    "Czerwona":                    "red",
}

DB = "players_stats_2024_25.db"
CREATE = """
CREATE TABLE IF NOT EXISTS stats (
    name TEXT PRIMARY KEY,
    matches TEXT, minutes TEXT, goals TEXT, shots TEXT, assists TEXT,
    interceptions TEXT, ball_recoveries TEXT, times_dribbled_past TEXT,
    successful_dribbles TEXT, duels_won TEXT, fouls TEXT, yellow TEXT, red TEXT
);
"""
UPSERT = """
INSERT INTO stats VALUES (
    :name, :matches, :minutes, :goals, :shots, :assists,
    :interceptions, :ball_recoveries, :times_dribbled_past,
    :successful_dribbles, :duels_won, :fouls, :yellow, :red)
ON CONFLICT(name) DO UPDATE SET
    matches=excluded.matches,
    minutes=excluded.minutes,
    goals=excluded.goals,
    shots=excluded.shots,
    assists=excluded.assists,
    interceptions=excluded.interceptions,
    ball_recoveries=excluded.ball_recoveries,
    times_dribbled_past=excluded.times_dribbled_past,
    successful_dribbles=excluded.successful_dribbles,
    duels_won=excluded.duels_won,
    fouls=excluded.fouls,
    yellow=excluded.yellow,
    red=excluded.red;
"""

# ------------------- helpers ------------------------

def extract_number(txt: str) -> str:
    """Zwraca *najbliższą w górę* liczbę całkowitą z tekstu, np. '0.4 (33%)' -> '1'."""
    m = re.search(r"[\d]+[\.,]?\d*", txt.replace(",", "."))
    if not m:
        return txt  # brak liczby, zwracamy oryginał
    num = float(m.group())
    return str(int(math.ceil(num)))


def expand_all(driver):
    for btn in driver.find_elements(By.CSS_SELECTOR, "button[aria-controls]"):
        if btn.get_attribute("aria-expanded") == "false":
            driver.execute_script("arguments[0].click();", btn)
            time.sleep(0.15)


def grab_stats(url: str, driver) -> dict:
    driver.get(url + "#tab:statistics")
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
    expand_all(driver)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    raw_name = soup.find("h1").get_text(strip=True)
    prefix = "Statystyki, punkty i gole zawodnika "
    name = raw_name[len(prefix):] if raw_name.startswith(prefix) else raw_name

    out = {v: "-" for v in LABELS.values()}

    for row in soup.select("div.d_flex.ai_center.jc_space-between"):
        spans = row.find_all("span")
        if len(spans) != 2:
            continue
        label, value = (s.get_text(strip=True) for s in spans)
        key = LABELS.get(label)
        if not key:
            continue
        out[key] = extract_number(value)

    out["name"] = name
    return out

# ------------------- main ---------------------------

def main():
    conn = sqlite3.connect(DB)
    conn.execute(CREATE)

    opt = webdriver.ChromeOptions()
    opt.add_argument("--headless=new")
    opt.add_argument("--no-sandbox")
    opt.add_argument("--disable-dev-shm-usage")

    with webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opt) as dr:
        for link in PLAYERS:
            try:
                stats = grab_stats(link, dr)
                conn.execute(UPSERT, stats)
                conn.commit()
                print(f"{stats['name']}, {stats['matches']}, {stats['minutes']}, {stats['goals']}, {stats['assists']}, {stats['interceptions']}, {stats['fouls']}, {stats['yellow']}, {stats['red']}")
            except Exception as e:
                print(f"Błąd przy {link}: {e}")

    conn.close()

if __name__ == "__main__":
    main()